# Generated by Django 3.2.5 on 2021-08-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210831_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imazh',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
