# Generated by Django 3.2.7 on 2021-09-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
