# Generated by Django 3.2.7 on 2021-09-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
