# Generated by Django 3.2.7 on 2021-09-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_second_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
