# Generated by Django 3.2.7 on 2021-09-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_streams_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streams',
        ),
    ]
